# .github/workflows/YB_ci.yml

# Name of the workflow
name: CI Pipeline

# Trigger the workflow on push or pull request events
on: [push, pull_request]

# Define the jobs to run
jobs:
  build:
    # Define the operating system to run the job on
    runs-on: github

    # Define the steps to run
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run linting
      - name: Run linting
        run: |
          pip install flake8
          flake8 .

      # Run tests
      - name: Run tests
        run: |
          pip install pytest
          pytest
